language: node_js

node_js:
  - '7.1'

before_install:
  - npm install -g npm@'>=4.0.2'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8