before_script:
  - sudo sed -i "s/precise/trusty/" /etc/apt/sources.list		
  - sudo apt-get update
  - sudo apt-get install -y pandoc pandoc-citeproc
  - sudo apt-get install -y texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-xetex texlive-lang-german texlive-bibtex-extra biber

script:
  - make html
  - make epub
  - make pdf
